'''
Description: 
Author: haichun feng
Date: 2024-03-29 14:27:25
LastEditor: haichun feng
LastEditTime: 2024-03-29 14:54:45
'''
import streamlit as st
import requests

# Title
st.title("Talk to LLMs")

# Text input for URL
# url = st.text_input("Enter URL", "https://localhost/generate")
url = "backend service URL"

button_text = "Start Talking"
# Button to trigger HTTP request
if st.button(button_text):
    try:
        # Make HTTP request
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for non-2xx status codes

        # # Display response data
        # st.success("Request successful!")
        # st.json(response.json())
    except requests.exceptions.RequestException as e:
        st.error(f"Request failed: {e}")

# Help text
st.text("**Script:**")

st.markdown("""
output the text generated by LLM.
""")